feat: add basic slash command
goverland-labs/discord-bot pull request #8
Opened 2023-12-07 00:27 UTC by marrakonda

- start slash command added
- welcome dm added

related to #1

2023-12-11 12:37 UTC, sche requested changes
Good job! 👏
Let's make a call and discuss it with a live demo.

2023-12-11 12:37 UTC, sche commented on requirements.txt
>  discord.py==2.3.2
can we remove discord.py?

2023-12-11 12:37 UTC, sche commented on .env.example
> +DISCORD_GUILD=1179544636499431445
Is it Goverland id?

2023-12-11 12:37 UTC, sche commented on .env.example
> +DISCORD_GUILD=1179544636499431445
I think it is better to make it as `<GUILD>` placeholder

2023-12-11 12:37 UTC, sche commented on src/run.py
> +            f"{bot.me.name} is connected to the following guild:\n"
Will it potentially show all the guilds/servers that connected this bot?

2023-12-11 12:37 UTC, sche commented on src/run.py
> +    async def on_member_join(member):
Will it be displayed for all new users joining Goverland server?
The scope of this bot should be limited to Server admins only. Use case: an admin adds the bot, configures the channel where updates will be coming to, adds/removes DAOs to follow.

2023-12-11 12:37 UTC, sche commented on src/run.py
> +    async def on_error(event, *args):
Could you please add a short comment / function doc describing a use case when it might happen?

2023-12-11 12:37 UTC, sche commented on src/run.py
> +        description="This is the first command I made!",
:)

2023-12-11 12:37 UTC, sche commented on src/run.py
> +    @bot.component("hello")
How about placing `"hello"` into a variable. It will reduce potential errors.

2023-12-21 22:36 UTC, marrakonda commented on requirements.txt
>  discord.py==2.3.2
Done

2023-12-21 22:42 UTC, marrakonda commented on src/run.py
> +            f"{bot.me.name} is connected to the following guild:\n"
Changed it to show all of them

2023-12-21 22:44 UTC, marrakonda commented on src/run.py
> +    async def on_member_join(member):
This is a nice way to say hi to every joiner of a guild. Nothing more will be available for a non-admin user.

2023-12-21 22:45 UTC, marrakonda commented on src/run.py
> +    async def on_error(event, *args):
Done

2023-12-22 00:34 UTC, marrakonda commented on src/run.py
> +    @bot.component("hello")
I did it a little bit different and more robust :)

2023-12-22 11:11 UTC, sche commented on src/run.py
> +DISCORD_GUILD = int(os.getenv("DISCORD_GUILD"))
Did we decide to remove DISCORD_GUILD last time?

2023-12-22 11:12 UTC, sche commented on src/run.py
> +    async def on_member_join(member):
So non-admin users will not see anything among bot slash commands?

2023-12-22 11:14 UTC, sche commented on src/run.py
> +    async def on_member_join(member):
I see later in code. Question closed.

2023-12-22 11:20 UTC, sche commented on src/run.py
> +    @bot.command(
I didn't test it, but I don't understand from the code how Admin commands are different from Regular user commands.

2023-12-22 11:21 UTC, sche approved these changes

2023-12-22 11:36 UTC, merged